# version: "3"
services:
  ipfs_host:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    # volumes:
    #   - $ipfs_staging:/export
    #   - $ipfs_data:/data/ipfs
  ipfs_api:
    build: https://github.com/TrustAllianceNZ/trustalliance-ipfs.git#main
    ports:
      - "3350:3350"
    environment:
      - PORT=3350
      - IPFS_BASE_URL=http://ipfs_host
  trust_node:
    image: trustalliance/trust-node:v0.0.1
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    command:
      - "--dev"
      - "--tmp"
      - "--ws-external"
  mvp_demo:
    build: https://github.com/jag-eagle-technology/trustalliance_sdk_mvp_demo.git#main
    environment:
      - NODE_URL=ws://trust_node:9944
      - IPFS_API_BASE_URL=http://ipfs_api:3350
      - IPFS_STORE_URL=http://ipfs_host:8080/ipfs/
